CREATE DATABASE IF NOT EXISTS devtone_local CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE devtone_local;

CREATE TABLE IF NOT EXISTS leads (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(190) NOT NULL,
  empresa VARCHAR(190) NOT NULL DEFAULT '-',
  email VARCHAR(190) NOT NULL,
  whatsapp VARCHAR(50) NOT NULL,
  segmento VARCHAR(190) NOT NULL DEFAULT '-',
  fonte VARCHAR(100) NOT NULL DEFAULT 'landing_page',
  status VARCHAR(50) DEFAULT 'novo',
  score INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS partial_leads (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(190) NOT NULL,
  email VARCHAR(190) DEFAULT NULL,
  whatsapp VARCHAR(50) DEFAULT NULL,
  step_reached INT NOT NULL DEFAULT 0,
  recovery_sent TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_conversations (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(190) DEFAULT NULL,
  user_email VARCHAR(190) DEFAULT NULL,
  edit_token VARCHAR(64) DEFAULT NULL,
  messages LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
